### ISSUE TITLE
Restarting stream

### ISSUE THREAD

**Issue by nick-jonas** [vin-ni/Google-Cloud-Speech-Node-Socket-Playground#4]
(This is more of an enhancement)

There is currently a time limit of 65 seconds for an audio stream  - have you thought about restarting the stream after each "isFinal" utterance?

```
{ Error: 11 OUT_OF_RANGE: Exceeded maximum allowed stream duration of 65 seconds.
    at Object.exports.createStatusError (/Users/njonas/Code/gweb-talkie/node_modules/grpc/src/common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (/Users/njonas/Code/gweb-talkie/node_modules/grpc/src/client.js:235:26)
    at ClientDuplexStream._receiveStatus (/Users/njonas/Code/gweb-talkie/node_modules/grpc/src/client.js:213:8)
    at Object.onReceiveStatus (/Users/njonas/Code/gweb-talkie/node_modules/grpc/src/client_interceptors.js:1316:15)
    at InterceptingListener._callNext (/Users/njonas/Code/gweb-talkie/node_modules/grpc/src/client_interceptors.js:590:42)
    at InterceptingListener.onReceiveStatus (/Users/njonas/Code/gweb-talkie/node_modules/grpc/src/client_interceptors.js:640:8)
    at /Users/njonas/Code/gweb-talkie/node_modules/grpc/src/client_interceptors.js:1136:18
  code: 11,
  metadata:
   Metadata {
     _internal_repr:
      { 'content-disposition': [Array],
        'google.rpc.debuginfo-bin': [Array],
        'grpc-status-details-bin': [Array] } },
  details: 'Exceeded maximum allowed stream duration of 65 seconds.' }
```

**Comment by vin-ni** [comment]
Hi Nick, 
yes this is an issue we should tackle.
I've found a very nice approach by [marciovm](https://github.com/marciovm/Speech-Forever). He uses directly websockets, which might even be nicer than using socket.io. To restart the stream, he calculates the volume of the microphone input and restarts it in a quiet moment. I guess i'd need to adapt this to my isFinal logic. I'll take a look.

**Comment by vin-ni** [comment]
does this work well?
I'm actually looking for that solution

**Comment by nick-jonas** [comment]
@vin-ni seems to work fine!

**Comment by vin-ni** [comment]
sweet!

**Comment by vin-ni** [comment]
i added it to the demo.
We forgot, that it still throws an error after 65 seconds of silence.
The best way is probably a combination of restarting the stream after each final sentence and restarting it after 45 seconds of silence
